"""create products table

Revision ID: dde7060d7740
Revises:
Create Date: 2026-04-13 14:16:53.888669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde7060d7740'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('supplier', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONTINUED', 'OUT_OF_STOCK', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
